#!/usr/bin/env bash
set -euo pipefail

DEPLOY_ROOT="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/../.." && pwd)"
SOURCE_ROOT="${HUSHINE_SOURCE_ROOT:-$(cd -- "${DEPLOY_ROOT}/.." && pwd)}"
OUT_DIR="${1:-${DEPLOY_ROOT}/db/generated}"
CURRENT_YEAR="$(date -u +%Y)"

declare -A migration_dirs=(
	[portfolio]="${SOURCE_ROOT}/core-service/internal/storage/migrations"
	[order]="${SOURCE_ROOT}/core-service/internal/order/storage/migrations"
	[control_panel]="${SOURCE_ROOT}/control-panel-service/internal/storage/migrations"
	[market_data_year]="${SOURCE_ROOT}/scraper/internal/storage/migrations"
)

for name in portfolio order control_panel market_data_year; do
	if [[ ! -d "${migration_dirs[$name]}" ]]; then
		echo "missing migration directory: ${migration_dirs[$name]}" >&2
		exit 1
	fi
done

mkdir -p "$OUT_DIR"

render_bundle() {
	local name="$1"
	local migration_dir="${migration_dirs[$name]}"
	local output="${OUT_DIR}/${name}.sql"
	local migration

	{
		printf '%s\n' '-- Generated by hushine-deploy/scripts/db/render-schema-bundle.sh'
		printf '%s\n' '-- Baseline/fresh rebuild only. Service migrations remain the schema source of truth.'
		printf '%s\n\n' '\set ON_ERROR_STOP on'
		printf '%s\n' 'BEGIN;'
		if [[ "$name" == "market_data_year" ]]; then
			printf '%s\n' 'CREATE TABLE IF NOT EXISTS schema_migrations ('
			printf '%s\n' '    filename TEXT PRIMARY KEY,'
			printf '%s\n' '    applied_at TIMESTAMPTZ NOT NULL DEFAULT NOW()'
			printf '%s\n\n' ');'
		fi

		while IFS= read -r migration; do
			printf '\n-- Source: %s\n' "${migration#${SOURCE_ROOT}/}"
			printf '%s\n' "$(<"$migration")"
			printf "INSERT INTO schema_migrations (filename) VALUES ('%s') ON CONFLICT (filename) DO NOTHING;\n" "$(basename "$migration")"
		done < <(find "$migration_dir" -maxdepth 1 -type f -name '*.sql' | sort)
		printf '%s\n' 'COMMIT;'
	} >"$output"
}

{
	printf '%s\n' '-- Generated by hushine-deploy/scripts/db/render-schema-bundle.sh'
	printf '%s\n' '\set ON_ERROR_STOP on'
	printf '%s\n' "SELECT format('CREATE DATABASE %I', name)"
	printf '%s\n' 'FROM (VALUES'
	printf "    ('portfolio'), ('order'), ('control_panel'), ('binance_%s'), ('okx_%s')\n" "$CURRENT_YEAR" "$CURRENT_YEAR"
	printf '%s\n' ') AS target(name)'
	printf '%s\n' 'WHERE NOT EXISTS (SELECT 1 FROM pg_database WHERE datname = target.name)'
	printf '%s\n' '\gexec'
} >"${OUT_DIR}/00_create_databases.psql"

for name in portfolio order control_panel market_data_year; do
	render_bundle "$name"
done

{
	printf '%s\n' '# Generated database bundles'
	printf '%s\n' ''
	printf '%s\n' 'Generated by `hushine-deploy/scripts/db/render-schema-bundle.sh` from the current service baselines.'
	printf '%s\n' ''
	printf '%s\n' 'These files are for Baseline/fresh rebuild and schema review. They are idempotent and preserve the `schema_migrations` ledger.'
	printf '%s\n' ''
	printf '%s\n' 'Run `00_create_databases.psql` against the admin database, then run each SQL bundle against its matching database. Run `market_data_year.sql` once per `{exchange}_${year}` database.'
} >"${OUT_DIR}/README.md"

echo "rendered schema bundles in ${OUT_DIR}"
