#!/usr/bin/env python3
from __future__ import annotations

import json
import os
from pathlib import Path
import re
import tempfile


DEPLOY_ROOT = Path(__file__).resolve().parents[1]
SOURCE_ROOT = Path(
    os.environ.get("HUSHINE_SOURCE_ROOT", str(DEPLOY_ROOT.parent))
).resolve()
GENERATED_HEADER = (
    "# Generated by hushine-deploy/scripts/prepare-local-configs.py. "
    "Do not edit.\n"
)
SHARED_HOST = "192.168.88.10"
LOCAL_CERT_DIR = Path(
    os.environ.get("HUSHINE_LOCAL_CERT_DIR", str(DEPLOY_ROOT / "certs"))
).expanduser().resolve()
LOCAL_CREDENTIAL_ENCRYPTION_KEY = "local-dev-credential-key-32bytes"


def _localize_yaml(
    relative_source: str,
    relative_target: str,
    *,
    control: bool = False,
    core: bool = False,
) -> None:
    source = SOURCE_ROOT / relative_source
    target = SOURCE_ROOT / relative_target
    text = source.read_text(encoding="utf-8")
    text = text.replace(SHARED_HOST, "127.0.0.1").replace(":19092", ":9092")
    if core:
        if re.search(r"(?m)^credential:\s*$", text):
            raise RuntimeError("core-service source config unexpectedly defines credential")
        text = (
            text.rstrip()
            + "\n\ncredential:\n"
            + f"  encryption_key: {json.dumps(LOCAL_CREDENTIAL_ENCRYPTION_KEY)}\n"
            + '  key_version: "local-v1"\n'
        )
    if control:
        pattern = re.compile(
            r"(?ms)^(runtime_channel_server:\n.*?^  tls:\n)"
            r"    enabled: (?:true|false)$"
        )
        text, count = pattern.subn(r"\1    enabled: true", text, count=1)
        if count != 1:
            raise RuntimeError("control-panel RuntimeChannel TLS block is missing")
        tls_paths = {
            "cert_file": LOCAL_CERT_DIR / "runtime-channel-server.pem",
            "key_file": LOCAL_CERT_DIR / "runtime-channel-server.key",
            "client_ca_file": LOCAL_CERT_DIR / "runtime-client-ca.pem",
            "client_ca_key_file": LOCAL_CERT_DIR / "runtime-client-ca.key",
        }
        for key, path in tls_paths.items():
            text, count = re.subn(
                rf'(?m)^    {key}:.*$',
                f"    {key}: {json.dumps(str(path))}",
                text,
                count=1,
            )
            if count != 1:
                raise RuntimeError(f"control-panel RuntimeChannel TLS {key} is missing")
    _write_private(target, GENERATED_HEADER + text)


def _localize_scraper_log() -> None:
    source = SOURCE_ROOT / "scraper/log-config.json"
    target = SOURCE_ROOT / "scraper/log-config.local.json"
    document = json.loads(source.read_text(encoding="utf-8"))
    document["kafka"] = {
        "enabled": True,
        "brokers": ["127.0.0.1:9092"],
        "topic": "app-logs",
        "topic_prefix": "app-logs",
    }
    document["tracing"] = {
        "enabled": True,
        "endpoint": "http://127.0.0.1:4318",
        "service_name": "scraper",
    }
    _write_private(target, json.dumps(document, indent=2) + "\n")


def _write_private(target: Path, content: str) -> None:
    if SHARED_HOST in content or ":19092" in content:
        raise RuntimeError(f"generated local config is not local: {target.name}")
    target.parent.mkdir(parents=True, exist_ok=True)
    descriptor, temporary_name = tempfile.mkstemp(
        prefix=f".{target.name}.", dir=target.parent
    )
    temporary = Path(temporary_name)
    try:
        with os.fdopen(descriptor, "w", encoding="utf-8", newline="\n") as output:
            output.write(content)
            output.flush()
            os.fsync(output.fileno())
        temporary.chmod(0o600)
        temporary.replace(target)
        target.chmod(0o600)
    finally:
        temporary.unlink(missing_ok=True)


def main() -> int:
    _localize_yaml(
        "core-service/config.yaml",
        "core-service/config.local.yaml",
        core=True,
    )
    for source, target in (
        (
            "gateway/quant-handler/config.yaml",
            "gateway/quant-handler/config.local.yaml",
        ),
        ("scraper/config.yaml", "scraper/config.local.yaml"),
    ):
        _localize_yaml(source, target)
    _localize_yaml(
        "control-panel-service/config.yaml",
        "control-panel-service/config.local.yaml",
        control=True,
    )
    _localize_scraper_log()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
